### ISSUE TITLE
Success not reported when using asynch client

### ISSUE THREAD

**Issue by upachler** [CleverTap/apns-http2#10]
When using the asynchronnous client, I pass my listener to ApnsClient.push(). While on failure, the listener's onFailure() method is called as it should be.
However, the listener's onSuccess() is never called, even though I receive messages.

I debugged a little through the library, and it would appear that OkHttp won't call the respective callback method. Is this a problem with OkHttp, or did I do something wrong in configuring apns-http2?

**Comment by judepereira** [comment]
I can't reproduce this. The success callback is called as expected. What does your code look like?

**Comment by upachler** [comment]
This is weird: It does sometimes work, sometimes not. Looks like a race condition..

**Comment by judepereira** [comment]
Closing, as this is not reproducible.
