### ISSUE TITLE
Notifications always successful, even when token has been invalidated

### ISSUE THREAD

**Issue by arielm** [CleverTap/apns-http2#11]
I'm able to send notifications which are properly received on some iOS device.

However, when uninstalling the corresponding app from the device, I would expect forthcoming notifications sent with the same token to fail with "Invalid Provider Token" error.

But this is not case: notifications are never failing.

**Comment by judepereira** [comment]
Hey Ariel, 
Once the app is uninstalled from the device, you should get DeviceTokenInactiveForTopic (410) as the error. 

Invalid provider token is only when the authentication tokens are invalid.

**Comment by arielm** [comment]
Hey Jude,
Thanks for your quick feedback.

Sorry, I was wrong regarding _InvalidProviderToken_ but still, my problem is that I never get any _DeviceTokenInactiveForTopic_ error, even after the app is uninstalled.

Some facts
1) I'm 100% sure that notifications reach my device before uninstallation.
2) After uninstallation: when using the HTTP1 Feedback Service (with an old version of Pushy), it properly detects my token.

**Comment by judepereira** [comment]
Thank you for the report, I'll take a look in the morning.

**Comment by arielm** [comment]
Follow-up: it's not an issue with CleverTap

The problem: you will never receive a 410 code when testing in development-mode on a single device with only one push-notification app enabled

More details: http://stackoverflow.com/questions/37410227/how-to-test-apple-push-notifications-feedback-service

Thanks!

**Comment by judepereira** [comment]
Thanks for the update @arielm!
