### ISSUE TITLE
Library leaks http connections on failed push

### ISSUE THREAD

**Issue by fizx** [CleverTap/apns-http2#14]
https://github.com/square/okhttp/issues/2311

**Comment by judepereira** [comment]
Hey @fizx, close() is always called on the body. https://github.com/CleverTap/apns-http2/blob/master/src/main/java/com/clevertap/apns/clients/SyncOkHttpApnsClient.java (line 261)

**Comment by judepereira** [comment]
Oh, I see that the async client is not closing the body. I'll do that right away.

**Comment by judepereira** [comment]
Fixed in ccdd83c.
