### ISSUE TITLE
java.io.IOException: unexpected end of stream on okhttp3.Address

### ISSUE THREAD

**Issue by jeasonyoung** [CleverTap/apns-http2#16]
java.io.IOException: unexpected end of stream on okhttp3.Address

**Comment by jeasonyoung** [comment]
cause by: java.io.EOFException: \n not found: size=176 content=000018040000
at okio.RealBufferedSource.readutf8LineStrict(RealBufferedSource.java:215)
at okhttp3.internal.http1.HttpCodec.readResponse(Http1Codec.java:191)

**Comment by www1350** [comment]
I meet the same problem

**Comment by www1350** [comment]
I resovle it!
add in pom.xml

```
<properties>
        <alpn-boot-version>8.1.9.v20160720</alpn-boot-version>
    </properties>

        <dependency>
            <groupId>org.mortbay.jetty.alpn</groupId>
            <artifactId>alpn-boot</artifactId>
            <version>${alpn-boot-version}</version>
        </dependency>



  <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>
                        -Xbootclasspath/p:${settings.localRepository}/org/mortbay/jetty/alpn/alpn-boot/${alpn-boot-version}/alpn-boot-${alpn-boot-version}.jar
                    </argLine>
                </configuration>
            </plugin>
        </plugins>
    </build>
```



![image](https://cloud.githubusercontent.com/assets/7789698/22962645/361ce990-f389-11e6-89c6-16ba00954eee.png)





focus in http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html

**Comment by jeasonyoung** [comment]
class: okhttp3.internal.io.RealConnection 
method: connectTls

// Success! Save the handshake and the ALPN protocol.
      String maybeProtocol = connectionSpec.supportsTlsExtensions()
          ? Platform.get().getSelectedProtocol(sslSocket)
          : null;
      socket = sslSocket;
      source = Okio.buffer(Okio.source(socket));
      sink = Okio.buffer(Okio.sink(socket));
      handshake = unverifiedHandshake;
      protocol = maybeProtocol != null
          ? Protocol.get(maybeProtocol)
          : Protocol.HTTP_1_1;
      success = true;

see class : okhttp3.internal.Platform

**Comment by judepereira** [comment]
Yes, you need the ALPN jar in the boot class path.

**Comment by www1350** [comment]
@jeasonyoung what is the meaning about RealConnection？

**Comment by jeasonyoung** [comment]
@www1350 我是通过报错信息发现 okhttp 使用的是http1 理论上它应该使用http2进行解析才对，然后寻找原因，okhttp是基于socket进行玩的，发现它在 Platform 类中通过反射的方式调用了 jdk或者说是系统的API来处理，优先调用的是Android(com.android.org.conscrypt.SSLParametersImpl)，然后使用的是 org.apache.harmony.xnet.provider.jsse.SSLParametersImpl，最后才是 ALPN(org.eclipse.jetty.alpn.ALPN), 而ALPN 中改写了未公开的sun.security.ssl下的API,所以才需要使用bootClassPath来覆盖，而 RealConnection 类是我发现这些的入口

**Comment by www1350** [comment]
你知道还有什么其他库支持http2吗？这个对jdk版本要求太过苛刻了

生命的意义不在于存在，云在青天水在瓶

**Comment by jeasonyoung** [comment]
netty有个netty-codec-http2 编解码器实现

**Comment by jeasonyoung** [comment]
似乎 没有严格按照 APNs的HTTP2协议来，比如 请求和返回中都没有apns-id字段

https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html

**Comment by rajibm2005** [comment]
I'm facing the same issue: java.io.IOException: unexpected end of stream on okhttp3.Address
while running this in JBoss Fuse 6.2.1 OSGI container. 

The alpn-boot is already in boot classpath of the container. 

Does anyone know how to resolve this ?

**Comment by chenqin091017** [comment]
> RealConnection

你好，你使用的java version是多少？我在java 11上面也碰到这个问题，你是怎么解决的？
