### ISSUE TITLE
Not support jdk1.7!

### ISSUE THREAD

**Issue by www1350** [CleverTap/apns-http2#17]
I found it is base on jdk1.8!
Can you make some changes to compatible with jdk1.8?

**Comment by judepereira** [comment]
This library depends on the Jetty ALPN client, and which requires 1.8. 1.7 will not be feasible.

**Comment by judepereira** [comment]
Looks like the ALPN client does support 1.7, however, I won't be adding 1.7 support due to time constraints. I'll definitely accept a pull request for 1.7 support though.
