### ISSUE TITLE
Proxy support 

### ISSUE THREAD

**Issue by rajibm2005** [CleverTap/apns-http2#18]
It seems apns-http2 library does not support proxy. 

I'm working on integration this into an OSGI container and needs to pass HTTP proxy details to make an outbound HTTP/2 call. 

Could you please change the builder to accept a proxy ? 

If required, I can offer help to make this change.

**Comment by judepereira** [comment]
Please use this method in the client builder to specify your own OkHttp client builder: https://github.com/CleverTap/apns-http2/blob/master/src/main/java/com/clevertap/apns/clients/ApnsClientBuilder.java#L90
