### ISSUE TITLE
java.io.EOFException

### ISSUE THREAD

**Issue by tommyjiajia** [CleverTap/apns-http2#20]
Hi 
     i used the following code to invoke apns service:
FileInputStream cert = new FileInputStream("path/Production.p12");
			final ApnsClient client = new ApnsClientBuilder()
			        .withProductionGateway()
			        .inSynchronousMode()
			        .withCertificate(cert)
			        .withPassword("pwd")
			        .withDefaultTopic("com")
			        .build();
/*			System.out.println("finish create client entity");*/
			Notification n = new Notification.Builder("2edbd61c4abdcd0da7fc671d7a89bc9fef84d3f474c94f5243f57cd")
	        .alertBody("Hello").build();
	/*		System.out.println("finish create n");*/
			NotificationResponse result = client.push(n);

but get the following response:
NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.io.EOFException: \n not found: size=176 content=0000180400000000000001000010000003000003e8000500004000000600001f...}

does any one face the same situation? i tried add the header rb.addHeader("Connection", "close"). it does not work for me?

Tommy

Tommy

**Comment by tommyjiajia** [comment]
can anybody give me some idea about this?

**Comment by hanxirui** [comment]
Did you send it successfully or do you have other java libraries recommended?

**Comment by judepereira** [comment]
This is most likely because you do not have the Jetty ALPN jar in your boot class path. Could you ensure that this is present?
