### ISSUE TITLE
java.io.IOExcetion

### ISSUE THREAD

**Issue by hanxirui** [CleverTap/apns-http2#21]
Hi
I used the following code to invoke apns service:
 FileInputStream cert = new FileInputStream("/home/test/DevPush.p12");

        final ApnsClient client = new ApnsClientBuilder()
                .withDevelopmentGateway()
                .inAsynchronousMode()
                .withCertificate(cert)
                .withPassword("pwd")
                .withDefaultTopic("com")
                .build();

        Notification n = new Notification.Builder("a05eefeebc42f07ee52bcf53f6d72d0cabc36268c6ef2c1a5199234d6a0b281c")
                .alertBody("Hello").build();

        client.push(n, new NotificationResponseListener() {
            @Override
            public void onSuccess(Notification notification) {
                System.out.println("success!");
            }
            @Override
            public void onFailure(Notification notification, NotificationResponse nr) {
                System.out.println("failure: " + nr);
            }
        });

Is anybody can help me,or if there have another library can send APNS2 success?

Thank you very much.

**Comment by judepereira** [comment]
Could you post the entire stack trace?
