### ISSUE TITLE
Need "content-available" and show toast, badge, sound feature

### ISSUE THREAD

**Issue by Bosian** [CleverTap/apns-http2#27]
When add key: "content-available" and value: "1" in custom key-value, will not alert, badge and sound

**Comment by judepereira** [comment]
According to the Apple docs, no alert is displayed if content-available is set.

**Comment by Bosian** [comment]
Can remove line 220 ~ 226 ? 

https://github.com/CleverTap/apns-http2/commit/0eabab309bded199f2be97879446e347a902531d

If need no toast and no sound, push sender can use "sound" and "alert" keep empty in APNS JSON format

**Comment by judepereira** [comment]
@Bosian What are you trying to achieve? If yous set content-available as 1, then according to the Apple docs, alert should be empty.

**Comment by Bosian** [comment]
I need collection push data and display to TableView in notification page of App, but also need show alert and sound for user. (I receive background push data and show local notification for user currency)

**Comment by judepereira** [comment]
So what you’d want to use is the new UserNotifications framework. This way, you can receive a silent push notification, and then create a local notification with the content you desire.

**Comment by erichsu** [comment]
Hi @judepereira, from the AppleDoc ([link](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html))

> To support a background update notification, make sure that the payload’s aps dictionary includes the content-available key with a value of 1. If there are user-visible updates that go along with the background update, **you can set the alert, sound, or badge keys** in the aps dictionary, as appropriate.

Should alert/badge/sound be empty with content-available 1 as your description?

I think what @Bosian want to achieve is both background updates and display alert by APS alone, not using UNNotification with local notification. 
It will be more flexible to send different purpose messages with Notification.
Is there any other concerns?

**Comment by judepereira** [comment]
Thanks @erichsu. Missed that somehow.

**Comment by erichsu** [comment]
Hi @judepereira, do you know when will this be deployed on CleverTap Official service?

**Comment by judepereira** [comment]
Please contact our official support for that particular information.
