### ISSUE TITLE
java.io.IOException: unexpected end of stream on okhttp3.Address

### ISSUE THREAD

**Issue by alex1985** [CleverTap/apns-http2#28]
Hi,
i got this error using java 9 and spring boot M7.
Any idea?

**Comment by FJ-Martinez** [comment]
I got the same error using java 8.

_NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.io.IOException: unexpected end of stream on okhttp3.Address@90c72b___

**Comment by judepereira** [comment]
This is most likely due to the ALPN library in the class path. Please see #24.

**Comment by alex1985** [comment]
i just added ALPN library with maven dependency. Are there any problems with tomcat embedded?

**Comment by judepereira** [comment]
It needs to be a part of your boot class path. May I see the relevant part of your pom.xml?

**Comment by zhouhao** [comment]
I have the same issue!
![image](https://user-images.githubusercontent.com/2281521/34472408-e6146f9c-ef2f-11e7-9399-7be21163e0bd.png)

The response is `null` here. 

```java
public Response index() {
        Notification n = new Notification.Builder("d056XXXXX...xxxx")
                .alertBody("Hello").build();

//        client.push(n, new NotificationResponseListener() {
//            @Override
//            public void onSuccess(Notification notification) {
//                System.out.println("success!");
//            }
//
//            @Override
//            public void onFailure(Notification notification, NotificationResponse nr) {
//                System.out.println("failure: " + nr);
//            }
//        });
        NotificationResponse result = client.push(n);
        System.out.println(result);

        return Response.noContent().build();
    }
```

**Comment by zhouhao** [comment]
I see your note, and I will have a try of ALPN first now.

**Comment by zhouhao** [comment]
Great! It works! And I can receive the push.

**Comment by FJ-Martinez** [comment]
I changed -VM arguments in eclipse of

> -Xbootclasspath/p:/Users/foo/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.9.v20160720/alpn-boot-8.1.9.v20160720-sources.jar

to: 

> -Xbootclasspath/p:/Users/foo/Downloads/alpn-boot-8.1.11.v20170118.jar

Now is working, but of result of notification is:

> _### NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.lang.NoSuchMethodError: sun.security.ssl.SupportedEllipticCurvesExtension.createExtension(Ljava/security/AlgorithmConstraints;)Lsun/security/ssl/SupportedEllipticCurvesExtension;}_

>

**Comment by FJ-Martinez** [comment]
The versions of JRE y ALPN is not properly.

I download the versión correct for my JRE and works.

**Comment by judepereira** [comment]
Glad to know it works @FJ-Martinez :)

**Comment by chenqin091017** [comment]
I have the same issue using java 9.
## Error Message
```
WARNING: All illegal access operations will be denied in a future release
java.io.IOException: unexpected end of stream on okhttp3.Address@2124d4cd
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:199)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
```
```
Caused by: java.io.EOFException: \n not found: size=159 content=000018040000000000000100001000000300000001000500004000000600001f...
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:201)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	... 67 more
```
## My Code
```
final ApnsClient client = new ApnsClientBuilder()
                    .inSynchronousMode()
                    .withProductionGateway()
                    .withApnsAuthKey("this is my auth key")
                    .withTeamID("this my teamed")
                    .withKeyID("this is key id")
                    .withDefaultTopic("this is topic")
                    .build();
            Notification n = new Notification.Builder("this is my device token")
                    .alertBody("Hello").build();
            client.push(n);
```
## Some Adjustment
- add class NetInterceptor implements Interceptor
```
@Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request().newBuilder()
                .addHeader("Connection","close").build();
        return chain.proceed(request);
    }
```
-  adjust com.bcc.im.apns.clients.ApnsClientBuilder
```
public static Builder createDefaultOkHttpClientBuilder() {
        Builder builder = new Builder();
        builder.connectTimeout(10, TimeUnit.SECONDS).writeTimeout(10, TimeUnit.SECONDS).readTimeout(30, TimeUnit.SECONDS);
        builder.connectionPool(new ConnectionPool(10, 10, TimeUnit.MINUTES));
        builder.addInterceptor(new NetInterceptor());//added code
        builder.retryOnConnectionFailure(true);//added code
        return builder;
    }
```
- I read apple apps documentation,so I try to add port 2197.
<img width="1578" alt="屏幕快照 2019-05-09 下午8 19 11" src="https://user-images.githubusercontent.com/17311435/57453059-f35b8400-7297-11e9-90ed-1d6daef36625.png">

##Result
But I can not solve the problem.Could you tell me the solution?
