### ISSUE TITLE
Support for Java 9

### ISSUE THREAD

**Issue by Vicinitor** [CleverTap/apns-http2#33]
Is it possible to use CleverTap for pushing to iOS without the Jetty alpn software?
I am using JRE and JDK 9.0.1 which is supposed to support HHTP/2 but get the "end of stream error".

**Comment by judepereira** [comment]
Not yet. We'll soon be updating the library to use the new HTTP/2 API in Java 9.

**Comment by Vicinitor** [comment]
Thanks for quick response. 
Can you please point me to the best description on how to install alpn?

**Comment by judepereira** [comment]
See [here](http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html).

**Comment by Vicinitor** [comment]
According to the ALPN version list there is no matching sw for Java 9. Does this mean I will have to revert back to JDK (?

**Comment by Vicinitor** [comment]
JDK 8 that should read

**Comment by judepereira** [comment]
I think so.
If you're open to beta testing, I think I'll be able to add Java 9 support for this library by early next week.

**Comment by Vicinitor** [comment]
Hello,
we are surely open for beta testing. Made simple tests with java-apns instead but interface coding in both iPhone and server remains.
Kind regards, Daniel  
--
Daniel Nilsson
Vicinitor AB
tel 0734-294000
----Ursprungligt meddelande----
Från : notifications@github.com
Datum : 2018-01-03 - 18:33 (CET)
Till : apns-http2@noreply.github.com
Kopia : daniel.nilsson@vicinitor.se, author@noreply.github.com
Ämne : Re: [CleverTap/apns-http2] Unexpected end of stream on okhttp3.Address using java 9 (#33)
I think so.
 If you're open to beta testing, I think I'll be able to add Java 9 support for this library by early next week.

**Comment by judepereira** [comment]
Glad to know. I'll keep you posted.

**Comment by judepereira** [comment]
@Vicinitor Could you checkout the java9 branch and test it? The library supports the new HttpClient in Java 9. Also, please read [this](https://github.com/CleverTap/apns-http2/wiki/Running-on-Java-9) before running your app.

**Comment by Vicinitor** [comment]
I am not sure how to do that. 
Found the branch but nothing seem to happen when I clone. 
Are the Maven identifiers the same?

**Comment by judepereira** [comment]
It's not published on maven central yet. To test it out, you could:
1. $ git clone https://github.com/CleverTap/apns-http2.git
2. $ cd apns-http2
3. $ git checkout java9
4. $ mvn package (this might fail at the javadoc step, but it would've generated the jar)

The last command will produce target/apns-http2-1.1.0.jar. This is without the JSON dependencies (jackson-core, jackson-databind). Since you're using Maven, just add the following:
```
    <dependencies>
        ...
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.8.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.8.4</version>
        </dependency>
        ...
    </dependencies>
```

Add target/apns-http2-1.1.0.jar as a JAR dependency (taken from [here](https://stackoverflow.com/a/27009642/2274894) directly):
```
<systemPath>/path/to/apns-http2-1.1.0.jar</systemPath>
```

This will complete the installation of this library for your app.

Now, when running your app, run it as follows:
```
java --add-opens jdk.incubator.httpclient/jdk.incubator.http=com.clevertap.apns .......
```

Note: Don't add ALPN to your app anymore.

**Comment by Vicinitor** [comment]
Sorry, but this goes far beyond my level of expertise, being a simple Android-Java and Swift programmer.

**Comment by judepereira** [comment]
Okay, you'd have to wait for a while until we make this available via Maven.

**Comment by judepereira** [comment]
Hey @Vicinitor, a quick update - Oracle has fixed the bug which we've reported. As soon as it's out in a newer version, I'll probably have this as a single downloadable JAR, with no additional requirements.

**Comment by judepereira** [comment]
Java 9/10 will not be supported, as Oracle won't back port the bug reported here: https://bugs.java.com/view_bug.do?bug_id=JDK-8194729

Moreover, the technique using reflection doesn't work in the newer versions of Java 9/10.
