### ISSUE TITLE
Problems with java9 branch

### ISSUE THREAD

**Issue by Stechmuck** [CleverTap/apns-http2#36]
Hi,

I had some problems to get the java9 brach running.

First I have to add
```java
	exports com.clevertap.apns;
	exports com.clevertap.apns.clients;
```
to the module-info.java.

After that, when sending a notification with p12 certificate, I got a InvalidProviderToken response.

To fix this, I added the sslContext to the httpClientBuilder in the SyncApnsClient constructor with InputStream.

```java
        this.client = httpClientBuilder
                .version(HttpClient.Version.HTTP_2)
                .sslContext(sslContext)
                .build();
```

Thanks for your great work.

**Comment by judepereira** [comment]
Thanks for the heads up @Stechmuck. If you've got it running successfully with provider certificates, could you please send a PR?

**Comment by Stechmuck** [comment]
Done -> #37
