### ISSUE TITLE
How to close ApnsClient?

### ISSUE THREAD

**Issue by 39301568aqq** [CleverTap/apns-http2#38]
How to close ApnsClient? If you modify the configuration file I want to re-initialize ApnsCilent, so how to close the old?

**Comment by judepereira** [comment]
Which configuration file are you referring to?

**Comment by 39301568aqq** [comment]
final ApnsClient client = new ApnsClientBuilder()
        .withProductionGateway()
        .inSynchronousMode()
        .withCertificate(cert)
        .withPassword("")
        .withDefaultTopic("<your app's topic>")
        .build();

When initialized, I want to change the following parameters.
withDefaultTopic,withProductionGateway,withCertificate

**Comment by judepereira** [comment]
Please see https://github.com/square/okhttp/pull/2589/commits/4de7d7f87e5d719394ad05c0c3d1d13270be8f57

You can get the underlying OkHttp client by calling ApnsClient#getHttpClient.

Note: There are different ways to close the client depending on whether you're using the asynchronous version or the synchronous version.
