### ISSUE TITLE
java.io.IOException: unexpected end of stream on okhttp3.Address@6c773ddd

### ISSUE THREAD

**Issue by promoscow** [CleverTap/apns-http2#43]
My code:

        FileInputStream cert;
        ApnsClient client = null;
        try {
            cert = new FileInputStream("./src/main/resources/data/prod.p12");

            client = new ApnsClientBuilder()
                    .withProductionGateway()
                    .inSynchronousMode()
                    .withCertificate(cert)
                    .withPassword("12345")
                    .withDefaultTopic("topic")
                    .build();
        } catch (Exception e) {
            e.printStackTrace();
        }

        ApnsClient finalClient = client;
        List<NotificationResponse> results = Arrays.stream(dto.getPushIds())
                .map(t -> Objects.requireNonNull(finalClient).push(new Notification.Builder(t)
                        .alertBody("test")
                        .alertTitle("test")
                        .badge(3)
                        .build()))
                .collect(Collectors.toList());

I reseive:

NotificationResponse:
error = null
httpStatusCode = -1
responseBody = null
cause = java.io.IOException: unexpected end of stream on okhttp3.Address@6c773ddd
    '-----> cause = java.io.EOFException: \n not found: size=247 content=0000180400000000000001000010000003000003e8000500004000000600001f...

**Comment by judepereira** [comment]
Which version of the JRE are you using? Have you put in the ALPN library in the boot classpath?

**Comment by promoscow** [comment]
> openjdk version "1.8.0_172"
> OpenJDK Runtime Environment (Zulu 8.30.0.1-linux64) (build 1.8.0_172-b01)
> OpenJDK 64-Bit Server VM (Zulu 8.30.0.1-linux64) (build 25.172-b01, mixed mode)

I added library to gradle project.

`compile 'com.clevertap.apns:apns-http2:1.0.3'`

**Comment by judepereira** [comment]
Please see the readme: https://github.com/CleverTap/apns-http2/blob/master/README.md
