### ISSUE TITLE
NotificationResponse{error=null, httpStatusCode=-1, responseBody='null', cause=java.io.IOException: unexpected end of stream on okhttp3.Address@3be322db}

### ISSUE THREAD

**Issue by tanshion** [CleverTap/apns-http2#6]
public static void main(String[] args) throws Exception {
        FileInputStream cert = new FileInputStream("aiyacloud_development.p12");
        final ApnsClient client = new ApnsClientBuilder().withOkHttp3().withDevelopmentGateway().inSynchronousMode().withCertificate(cert).withPassword("123456").build();
        client.start();
        Notification n = new Notification.Builder("1e24f9463ee436882086b88015e605a8c51c6fb386846f09695b40c3f7ea64b1").alertBody("Hello").build();
        NotificationResponse result = client.push(n);
        System.out.println(result);
    }

**Comment by www1350** [comment]
how to resolve it？

**Comment by nthung82** [comment]
any solution for that?
I got the same too
