### ISSUE TITLE
Cannot customize OkHttp Client

### ISSUE THREAD

**Issue by upachler** [CleverTap/apns-http2#7]
Hello,

I need to operate apns-http2 behind an authenticated HTTP Proxy, but found that there is no support for that in the library. OkHttp itself supports this kind of configuration, but apns-http2 currently won't allow access to the OkHttpClient.Builder that would allow this kind of customization.

**Comment by upachler** [comment]
Added pull request with changes I made to the library to resolve this problem:
https://github.com/CleverTap/apns-http2/pull/8

**Comment by judepereira** [comment]
Continuing this on #8
