### ISSUE TITLE
If jdk8 version > 8u252,  does it still need to add Jetty's ALPN JAR dependency?

### ISSUE THREAD

**Issue by FJEagle** [CleverTap/apns-http2#81]
According to the post: https://webtide.com/jetty-alpn-java-8u252/,  jdk8 (>8u252) has backported the ALPN API from java 9.

My project is using jdk1.8.281.

But I still get the error log:    ALPN callback dropped: SPDY and HTTP/2 are disabled. Is alpn-boot on the boot class path?

If jdk8 version > 8u252,  does it still need to add Jetty's ALPN JAR dependency to use this libarary? thanks.

**Comment by FJEagle** [comment]
According to https://github.com/jetty-project/jetty-alpn,
if jdk8 version > 8u252, I must NOT add the Jetty ALPN boot jar.

So, if jdk8 version > 8u252, this library still need to add Jetty's ALPN JAR dependency, what is the right way to  add the alpn api dependecy?

**Comment by apolds** [comment]
See #73

**Comment by FJEagle** [comment]
> 
> 
> See #73

Thanks, I have tried the build from your fork, and it seems all work well.
